MASTER_COLUMNS = [
    ("Project ID", "TEXT_NUMBER", True),
    ("Market", "PICKLIST", False),
    ("Task Name", "TEXT_NUMBER", False),
    ("Address", "TEXT_NUMBER", False),
    ("City", "TEXT_NUMBER", False),
    ("CRQ Number", "TEXT_NUMBER", False),
    ("Daily No", "TEXT_NUMBER", False),
    ("Due Date", "DATE", False),
    ("Status", "PICKLIST", False),
    ("Assigned Technician", "CONTACT_LIST", False),
    ("Priority", "PICKLIST", False),
    ("Date Received", "DATE", False),
    ("Date Assigned", "DATE", False),
    ("Date Started", "DATE", False),
    ("Date Field Completed", "DATE", False),
    ("Work Performed", "TEXT_NUMBER", False),
    ("Manager Notes", "TEXT_NUMBER", False),
    ("Customer Notes", "TEXT_NUMBER", False),
    ("Billing Status", "PICKLIST", False),
    ("Zoho Invoice ID", "TEXT_NUMBER", False),
    ("Invoice Number", "TEXT_NUMBER", False),
    ("Invoice Date", "DATE", False),
    ("Invoice Amount", "CURRENCY", False),
    ("Payment Status", "PICKLIST", False),
    ("Payment Date", "DATE", False),
    ("Payment Number", "TEXT_NUMBER", False),
    ("Amount Paid", "CURRENCY", False),
    ("Balance", "CURRENCY", False),
    ("Billing Fingerprint", "TEXT_NUMBER", False),
    ("Billing Package Path", "TEXT_NUMBER", False),
    ("Archived", "CHECKBOX", False),
]

SHEET_DEFINITIONS = {
    "Graycliff Small Projects - Master": MASTER_COLUMNS,
    "Graycliff Billing Batches": [
        ("Batch ID", "TEXT_NUMBER", True), ("Market", "PICKLIST", False),
        ("Invoice Number", "TEXT_NUMBER", False), ("Zoho Invoice ID", "TEXT_NUMBER", False),
        ("Invoice Date", "DATE", False), ("Total", "CURRENCY", False),
        ("Status", "PICKLIST", False), ("Job Count", "TEXT_NUMBER", False),
        ("ZIP Path", "TEXT_NUMBER", False), ("Created By", "CONTACT_LIST", False),
    ],
    "Graycliff Payments": [
        ("Payment Number", "TEXT_NUMBER", True), ("Payment Date", "DATE", False),
        ("Payment Total", "CURRENCY", False), ("Invoice Number", "TEXT_NUMBER", False),
        ("Amount Applied", "CURRENCY", False), ("Unapplied Amount", "CURRENCY", False),
        ("Remittance File", "TEXT_NUMBER", False), ("Status", "PICKLIST", False),
    ],
    "Graycliff Payment Matches": [
        ("Match ID", "TEXT_NUMBER", True), ("Payment Number", "TEXT_NUMBER", False),
        ("Daily No", "TEXT_NUMBER", False), ("Project ID", "TEXT_NUMBER", False),
        ("Quantity Fingerprint", "TEXT_NUMBER", False), ("Amount", "CURRENCY", False),
        ("Source Date", "DATE", False), ("Match Method", "PICKLIST", False),
        ("Confidence", "TEXT_NUMBER", False), ("Reviewed By", "CONTACT_LIST", False),
        ("Reviewed At", "DATE", False), ("Notes", "TEXT_NUMBER", False),
    ],
    "Graycliff Users": [
        ("Email", "TEXT_NUMBER", True), ("Display Name", "TEXT_NUMBER", False),
        ("Role", "PICKLIST", False), ("Markets", "TEXT_NUMBER", False),
        ("Active", "CHECKBOX", False),
    ],
    "Graycliff Configuration": [
        ("Key", "TEXT_NUMBER", True), ("Value", "TEXT_NUMBER", False),
        ("Description", "TEXT_NUMBER", False),
    ],
}
